import React, { useState, useEffect } from 'react';
import { Trash2 } from 'lucide-react';

// ============================================================
// REQUIRED DATABASE SETUP — run once in the Supabase SQL editor:
//
// create table if not exists payments (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id) not null,
//   amount numeric not null,
//   payment_mode text not null default 'cash' check (payment_mode in ('cash','bank','cheque','upi')),
//   reference_no text,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists receipts (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id) not null,
//   amount numeric not null,
//   receipt_mode text not null default 'cash' check (receipt_mode in ('cash','bank','cheque','upi')),
//   reference_no text,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists account_vouchers (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   debit_ledger_id bigint references ledgers(id) not null,
//   credit_ledger_id bigint references ledgers(id) not null,
//   amount numeric not null,
//   narration text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// Enable Realtime on all three new tables (Database → Replication) so this
// module live-syncs, same as your other tables.
// ============================================================

// Pass in your existing `supabase` client and `userRole` from App.js as props.
// Optionally pass `subTab`/`onSubTabChange` to control navigation from an
// external sidebar (same pattern as ProductionModule/TransactionModule/MastersModule).
export default function FinancialModule({ supabase, userRole, subTab: subTabProp, onSubTabChange }) {
  const [internalSubTab, setInternalSubTab] = useState('payment');
  const subTab = subTabProp || internalSubTab;
  const setSubTab = onSubTabChange || setInternalSubTab;
  const [error, setError] = useState('');

  const tabs = [
    ['payment', '💵 Payment'],
    ['receipt', '🧾 Receipt'],
    ['voucher', '📑 Account Voucher'],
  ];

  return (
    <div className="space-y-4">
      {error && (
        <div className="bg-red-50 border-l-4 border-red-500 p-3 rounded-lg">
          <p className="text-sm text-red-700">⚠️ {error}</p>
        </div>
      )}

      {!subTabProp && (
        <div className="flex gap-2 flex-wrap">
          {tabs.map(([key, label]) => (
            <button
              key={key}
              onClick={() => setSubTab(key)}
              className={`px-3 py-2 rounded-lg font-semibold text-xs ${subTab === key ? 'bg-red-800 text-white' : 'bg-white text-gray-700'}`}
            >
              {label}
            </button>
          ))}
        </div>
      )}

      {subTab === 'payment' && <Payment supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'receipt' && <Receipt supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'voucher' && <AccountVoucher supabase={supabase} setError={setError} userRole={userRole} />}
    </div>
  );
}

// ---------- shared helpers (same pattern as the other modules) ----------
function useSynced(supabase, table, selectStr, setError, orderCol = 'id') {
  const [rows, setRows] = useState([]);
  const load = async () => {
    const { data, error } = await supabase.from(table).select(selectStr || '*').order(orderCol, { ascending: false });
    if (error) setError(error.message); else setRows(data || []);
  };
  useEffect(() => {
    load();
    const ch = supabase.channel(`${table}-sync`)
      .on('postgres_changes', { event: '*', schema: 'public', table }, load).subscribe();
    return () => supabase.removeChannel(ch);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return { rows, load };
}

function useLookup(supabase, table, setError, filterFn) {
  const [rows, setRows] = useState([]);
  useEffect(() => {
    supabase.from(table).select('*').order('id').then(({ data, error }) => {
      if (error) setError(error.message); else setRows(filterFn ? (data || []).filter(filterFn) : (data || []));
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return rows;
}

function sumBy(rows, groupKeyFn, valueKey = 'quantity') {
  const totals = {};
  for (const r of rows) {
    const key = groupKeyFn(r);
    if (key === null || key === undefined) continue;
    totals[key] = (totals[key] || 0) + (r[valueKey] || 0);
  }
  return totals;
}

function StockGrid({ title, entries }) {
  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <h3 className="text-lg font-bold mb-3">{title}</h3>
      {entries.length === 0 ? (
        <p className="text-gray-400 text-sm">No data yet</p>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {entries.map(([label, val]) => (
            <div key={label} className="p-3 rounded-lg border-2 bg-blue-50 border-blue-200">
              <p className="text-xs font-bold truncate">{label}</p>
              <p className="text-xl font-bold text-blue-600">{typeof val === 'number' ? val.toLocaleString() : val}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function FormPanel({ title, children, onSave, tableRows, columns, onDelete }) {
  return (
    <div className="grid lg:grid-cols-3 gap-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl font-bold mb-4">{title}</h2>
        <div className="space-y-3">
          {children}
          <button onClick={onSave} className="w-full bg-red-700 text-white font-bold py-2 rounded-md">Save</button>
        </div>
      </div>
      <div className="lg:col-span-2 bg-white rounded-lg shadow-md p-6 overflow-x-auto">
        {tableRows.length === 0 ? (
          <p className="text-gray-400">No entries yet</p>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                {columns.map((c) => <th key={c.key} className="px-3 py-2 text-left">{c.label}</th>)}
                <th className="px-3 py-2">Del</th>
              </tr>
            </thead>
            <tbody>
              {tableRows.map((row) => (
                <tr key={row.id} className="border-b">
                  {columns.map((c) => (
                    <td key={c.key} className="px-3 py-2">{c.render ? c.render(row) : row[c.key]}</td>
                  ))}
                  <td className="px-3 py-2 text-center">
                    <button onClick={() => onDelete(row.id)} className="text-red-500"><Trash2 size={16} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

const todayStr = () => new Date().toISOString().split('T')[0];

// ---------------- Payment ----------------
function Payment({ supabase, setError, userRole }) {
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { date: todayStr(), ledgerId: '', amount: '', paymentMode: 'cash', referenceNo: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'payments', '*, ledgers(ledger_name, ledger_type)', setError, 'date');

  const save = async () => {
    if (!form.ledgerId || !form.amount) return;
    const { error } = await supabase.from('payments').insert({
      date: form.date, ledger_id: form.ledgerId, amount: parseFloat(form.amount),
      payment_mode: form.paymentMode, reference_no: form.referenceNo || null,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, ledgerId: p.ledgerId, paymentMode: p.paymentMode }));
  };

  const byLedger = sumBy(rows, (r) => r.ledgers?.ledger_name, 'amount');

  return (
    <div className="space-y-4">
      <StockGrid title="Total Paid — by Ledger (₹)" entries={Object.entries(byLedger)} />
      <FormPanel
        title="Record Payment"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('payments').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'ledger', label: 'Paid To', render: (r) => r.ledgers?.ledger_name },
          { key: 'amount', label: 'Amount (₹)' },
          { key: 'payment_mode', label: 'Mode' },
          { key: 'reference_no', label: 'Ref #' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Paid To (Ledger)</option>
          {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name} ({l.ledger_type})</option>)}
        </select>
        <input type="number" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} placeholder="Amount (₹)" className="w-full px-3 py-2 border rounded-md" />
        <select value={form.paymentMode} onChange={(e) => setForm((p) => ({ ...p, paymentMode: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="cash">Cash</option>
          <option value="bank">Bank Transfer</option>
          <option value="cheque">Cheque</option>
          <option value="upi">UPI</option>
        </select>
        <input type="text" value={form.referenceNo} onChange={(e) => setForm((p) => ({ ...p, referenceNo: e.target.value }))} placeholder="Cheque/UTR/Ref # (optional)" className="w-full px-3 py-2 border rounded-md" />
        <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
    </div>
  );
}

// ---------------- Receipt ----------------
function Receipt({ supabase, setError, userRole }) {
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { date: todayStr(), ledgerId: '', amount: '', receiptMode: 'cash', referenceNo: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'receipts', '*, ledgers(ledger_name, ledger_type)', setError, 'date');

  const save = async () => {
    if (!form.ledgerId || !form.amount) return;
    const { error } = await supabase.from('receipts').insert({
      date: form.date, ledger_id: form.ledgerId, amount: parseFloat(form.amount),
      receipt_mode: form.receiptMode, reference_no: form.referenceNo || null,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, ledgerId: p.ledgerId, receiptMode: p.receiptMode }));
  };

  const byLedger = sumBy(rows, (r) => r.ledgers?.ledger_name, 'amount');

  return (
    <div className="space-y-4">
      <StockGrid title="Total Received — by Ledger (₹)" entries={Object.entries(byLedger)} />
      <FormPanel
        title="Record Receipt"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('receipts').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'ledger', label: 'Received From', render: (r) => r.ledgers?.ledger_name },
          { key: 'amount', label: 'Amount (₹)' },
          { key: 'receipt_mode', label: 'Mode' },
          { key: 'reference_no', label: 'Ref #' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Received From (Ledger)</option>
          {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name} ({l.ledger_type})</option>)}
        </select>
        <input type="number" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} placeholder="Amount (₹)" className="w-full px-3 py-2 border rounded-md" />
        <select value={form.receiptMode} onChange={(e) => setForm((p) => ({ ...p, receiptMode: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="cash">Cash</option>
          <option value="bank">Bank Transfer</option>
          <option value="cheque">Cheque</option>
          <option value="upi">UPI</option>
        </select>
        <input type="text" value={form.referenceNo} onChange={(e) => setForm((p) => ({ ...p, referenceNo: e.target.value }))} placeholder="Cheque/UTR/Ref # (optional)" className="w-full px-3 py-2 border rounded-md" />
        <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
    </div>
  );
}

// ---------------- Account Voucher ----------------
// A simple double-entry style journal voucher: value moves from a debit
// ledger to a credit ledger (e.g. correcting misposted entries, recording
// internal transfers, adjustments, etc.)
function AccountVoucher({ supabase, setError, userRole }) {
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { date: todayStr(), debitLedgerId: '', creditLedgerId: '', amount: '', narration: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(
    supabase, 'account_vouchers',
    '*, debit_ledger:debit_ledger_id(ledger_name), credit_ledger:credit_ledger_id(ledger_name)',
    setError, 'date'
  );

  const save = async () => {
    if (!form.debitLedgerId || !form.creditLedgerId || !form.amount) return;
    if (form.debitLedgerId === form.creditLedgerId) { setError('Debit and Credit ledger must be different'); return; }
    const { error } = await supabase.from('account_vouchers').insert({
      date: form.date, debit_ledger_id: form.debitLedgerId, credit_ledger_id: form.creditLedgerId,
      amount: parseFloat(form.amount), narration: form.narration || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  return (
    <FormPanel
      title="Add Account Voucher"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('account_vouchers').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'date', label: 'Date' },
        { key: 'debit', label: 'Debit', render: (r) => r.debit_ledger?.ledger_name },
        { key: 'credit', label: 'Credit', render: (r) => r.credit_ledger?.ledger_name },
        { key: 'amount', label: 'Amount (₹)' },
        { key: 'narration', label: 'Narration' },
      ]}
    >
      <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <select value={form.debitLedgerId} onChange={(e) => setForm((p) => ({ ...p, debitLedgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Debit Ledger</option>
        {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name}</option>)}
      </select>
      <select value={form.creditLedgerId} onChange={(e) => setForm((p) => ({ ...p, creditLedgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Credit Ledger</option>
        {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name}</option>)}
      </select>
      <input type="number" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} placeholder="Amount (₹)" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.narration} onChange={(e) => setForm((p) => ({ ...p, narration: e.target.value }))} placeholder="Narration (reason for this entry)" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}
