import React, { useState, useEffect } from 'react';
import { Trash2 } from 'lucide-react';

// ============================================================
// REQUIRED DATABASE SETUP — run once in the Supabase SQL editor:
//
// create table if not exists labour_rates (
//   id bigint generated by default as identity primary key,
//   work_type text not null,
//   rate numeric not null,
//   unit text default '1000 bricks',
//   effective_date date not null,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists kat_setups (
//   id bigint generated by default as identity primary key,
//   item_id bigint references items(id),
//   kat_name text not null,
//   bricks_per_kat numeric not null,
//   rate_per_kat numeric,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists commission_setups (
//   id bigint generated by default as identity primary key,
//   sale_agent_id bigint references sale_agents(id) not null,
//   item_id bigint references items(id),
//   commission_type text not null check (commission_type in ('percentage','fixed')),
//   commission_value numeric not null,
//   effective_date date not null,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists items_opening (
//   id bigint generated by default as identity primary key,
//   item_id bigint references items(id) not null,
//   stack_number int not null,
//   opening_quantity numeric not null,
//   opening_date date not null,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// create table if not exists ledgers_opening (
//   id bigint generated by default as identity primary key,
//   ledger_id bigint references ledgers(id) not null,
//   opening_balance numeric not null,
//   balance_type text not null check (balance_type in ('debit','credit')),
//   opening_date date not null,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// Enable Realtime on all five new tables (Database → Replication) so this
// module live-syncs, same as your other tables.
// ============================================================

// Pass in your existing `supabase` client and `userRole` from App.js as props.
// Optionally pass `subTab`/`onSubTabChange` to control navigation from an
// external sidebar (same pattern as the other modules).
export default function InitialSettingsModule({ supabase, userRole, subTab: subTabProp, onSubTabChange }) {
  const [internalSubTab, setInternalSubTab] = useState('labourRates');
  const subTab = subTabProp || internalSubTab;
  const setSubTab = onSubTabChange || setInternalSubTab;
  const [error, setError] = useState('');

  const tabs = [
    ['labourRates', '👷 Labour Rates'],
    ['katSetup', '⚙️ Kat Setup'],
    ['commissionSetup', '💼 Commission Setup'],
    ['itemsOpening', '📦 Items Opening'],
    ['ledgersOpening', '📒 Ledgers Opening'],
  ];

  return (
    <div className="space-y-4">
      {error && (
        <div className="bg-red-50 border-l-4 border-red-500 p-3 rounded-lg">
          <p className="text-sm text-red-700">⚠️ {error}</p>
        </div>
      )}

      {!subTabProp && (
        <div className="flex gap-2 flex-wrap">
          {tabs.map(([key, label]) => (
            <button
              key={key}
              onClick={() => setSubTab(key)}
              className={`px-3 py-2 rounded-lg font-semibold text-xs ${subTab === key ? 'bg-red-800 text-white' : 'bg-white text-gray-700'}`}
            >
              {label}
            </button>
          ))}
        </div>
      )}

      {subTab === 'labourRates' && <LabourRates supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'katSetup' && <KatSetup supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'commissionSetup' && <CommissionSetup supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'itemsOpening' && <ItemsOpening supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'ledgersOpening' && <LedgersOpening supabase={supabase} setError={setError} userRole={userRole} />}
    </div>
  );
}

// ---------- shared helpers (same pattern as the other modules) ----------
function useSynced(supabase, table, selectStr, setError, orderCol = 'id') {
  const [rows, setRows] = useState([]);
  const load = async () => {
    const { data, error } = await supabase.from(table).select(selectStr || '*').order(orderCol, { ascending: false });
    if (error) setError(error.message); else setRows(data || []);
  };
  useEffect(() => {
    load();
    const ch = supabase.channel(`${table}-sync`)
      .on('postgres_changes', { event: '*', schema: 'public', table }, load).subscribe();
    return () => supabase.removeChannel(ch);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return { rows, load };
}

function useLookup(supabase, table, setError, filterFn) {
  const [rows, setRows] = useState([]);
  useEffect(() => {
    supabase.from(table).select('*').order('id').then(({ data, error }) => {
      if (error) setError(error.message); else setRows(filterFn ? (data || []).filter(filterFn) : (data || []));
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return rows;
}

function FormPanel({ title, children, onSave, tableRows, columns, onDelete }) {
  return (
    <div className="grid lg:grid-cols-3 gap-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl font-bold mb-4">{title}</h2>
        <div className="space-y-3">
          {children}
          <button onClick={onSave} className="w-full bg-red-700 text-white font-bold py-2 rounded-md">Save</button>
        </div>
      </div>
      <div className="lg:col-span-2 bg-white rounded-lg shadow-md p-6 overflow-x-auto">
        {tableRows.length === 0 ? (
          <p className="text-gray-400">No entries yet</p>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                {columns.map((c) => <th key={c.key} className="px-3 py-2 text-left">{c.label}</th>)}
                <th className="px-3 py-2">Del</th>
              </tr>
            </thead>
            <tbody>
              {tableRows.map((row) => (
                <tr key={row.id} className="border-b">
                  {columns.map((c) => (
                    <td key={c.key} className="px-3 py-2">{c.render ? c.render(row) : row[c.key]}</td>
                  ))}
                  <td className="px-3 py-2 text-center">
                    <button onClick={() => onDelete(row.id)} className="text-red-500"><Trash2 size={16} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

const todayStr = () => new Date().toISOString().split('T')[0];

// ---------------- Labour Rates ----------------
function LabourRates({ supabase, setError, userRole }) {
  const empty = { workType: '', rate: '', unit: '1000 bricks', effectiveDate: todayStr(), remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'labour_rates', '*', setError, 'effective_date');

  const save = async () => {
    if (!form.workType || !form.rate) return;
    const { error } = await supabase.from('labour_rates').insert({
      work_type: form.workType, rate: parseFloat(form.rate), unit: form.unit || null,
      effective_date: form.effectiveDate, remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  return (
    <FormPanel
      title="Add Labour Rate"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('labour_rates').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'effective_date', label: 'Effective From' },
        { key: 'work_type', label: 'Work Type' },
        { key: 'rate', label: 'Rate (₹)' },
        { key: 'unit', label: 'Per' },
        { key: 'remarks', label: 'Remarks' },
      ]}
    >
      <input type="text" value={form.workType} onChange={(e) => setForm((p) => ({ ...p, workType: e.target.value }))} placeholder="Work Type (e.g. Pathai, Jalai, Nikasi)" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.rate} onChange={(e) => setForm((p) => ({ ...p, rate: e.target.value }))} placeholder="Rate (₹)" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.unit} onChange={(e) => setForm((p) => ({ ...p, unit: e.target.value }))} placeholder="Per (e.g. 1000 bricks, day)" className="w-full px-3 py-2 border rounded-md" />
      <input type="date" value={form.effectiveDate} onChange={(e) => setForm((p) => ({ ...p, effectiveDate: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}

// ---------------- Kat Setup ----------------
// "Kat" = a counting/measurement unit used for labour payment (e.g. how many
// bricks make up one Kat, and what's paid per Kat for a given item).
function KatSetup({ supabase, setError, userRole }) {
  const items = useLookup(supabase, 'items', setError);
  const empty = { itemId: '', katName: '', bricksPerKat: '', ratePerKat: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'kat_setups', '*, items(item_name)', setError, 'id');

  const save = async () => {
    if (!form.katName || !form.bricksPerKat) return;
    const { error } = await supabase.from('kat_setups').insert({
      item_id: form.itemId || null, kat_name: form.katName, bricks_per_kat: parseFloat(form.bricksPerKat),
      rate_per_kat: form.ratePerKat ? parseFloat(form.ratePerKat) : null, remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  return (
    <FormPanel
      title="Add Kat Setup"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('kat_setups').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'kat_name', label: 'Kat Name' },
        { key: 'item', label: 'Item', render: (r) => r.items?.item_name || 'All Items' },
        { key: 'bricks_per_kat', label: 'Bricks / Kat' },
        { key: 'rate_per_kat', label: 'Rate / Kat (₹)', render: (r) => r.rate_per_kat ?? '-' },
      ]}
    >
      <input type="text" value={form.katName} onChange={(e) => setForm((p) => ({ ...p, katName: e.target.value }))} placeholder="Kat Name (e.g. Kat-A)" className="w-full px-3 py-2 border rounded-md" />
      <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Applies to All Items</option>
        {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
      </select>
      <input type="number" value={form.bricksPerKat} onChange={(e) => setForm((p) => ({ ...p, bricksPerKat: e.target.value }))} placeholder="Bricks per Kat" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.ratePerKat} onChange={(e) => setForm((p) => ({ ...p, ratePerKat: e.target.value }))} placeholder="Rate per Kat (₹, optional)" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}

// ---------------- Commission Setup ----------------
function CommissionSetup({ supabase, setError, userRole }) {
  const saleAgents = useLookup(supabase, 'sale_agents', setError);
  const items = useLookup(supabase, 'items', setError);
  const empty = { saleAgentId: '', itemId: '', commissionType: 'percentage', commissionValue: '', effectiveDate: todayStr(), remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'commission_setups', '*, sale_agents(agent_name), items(item_name)', setError, 'effective_date');

  const save = async () => {
    if (!form.saleAgentId || !form.commissionValue) return;
    const { error } = await supabase.from('commission_setups').insert({
      sale_agent_id: form.saleAgentId, item_id: form.itemId || null, commission_type: form.commissionType,
      commission_value: parseFloat(form.commissionValue), effective_date: form.effectiveDate,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, saleAgentId: p.saleAgentId, commissionType: p.commissionType }));
  };

  return (
    <FormPanel
      title="Add Commission Setup"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('commission_setups').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'effective_date', label: 'Effective From' },
        { key: 'agent', label: 'Agent', render: (r) => r.sale_agents?.agent_name },
        { key: 'item', label: 'Item', render: (r) => r.items?.item_name || 'All Items' },
        { key: 'commission_value', label: 'Value', render: (r) => r.commission_type === 'percentage' ? `${r.commission_value}%` : `₹${r.commission_value}` },
      ]}
    >
      <select value={form.saleAgentId} onChange={(e) => setForm((p) => ({ ...p, saleAgentId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Sale Agent</option>
        {saleAgents.map((a) => <option key={a.id} value={a.id}>{a.agent_name}</option>)}
      </select>
      <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Applies to All Items</option>
        {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
      </select>
      <select value={form.commissionType} onChange={(e) => setForm((p) => ({ ...p, commissionType: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="percentage">Percentage (%)</option>
        <option value="fixed">Fixed (₹ per 1000)</option>
      </select>
      <input type="number" value={form.commissionValue} onChange={(e) => setForm((p) => ({ ...p, commissionValue: e.target.value }))} placeholder="Value" className="w-full px-3 py-2 border rounded-md" />
      <input type="date" value={form.effectiveDate} onChange={(e) => setForm((p) => ({ ...p, effectiveDate: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}

// ---------------- Items Opening ----------------
// Sets the starting stock for an item/stack at the beginning of your books —
// this also pushes the value straight into your live `inventory` table.
function ItemsOpening({ supabase, setError, userRole }) {
  const items = useLookup(supabase, 'items', setError);
  const empty = { itemId: '', stackNumber: '1', openingQuantity: '', openingDate: todayStr(), remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'items_opening', '*, items(item_name)', setError, 'opening_date');

  const save = async () => {
    if (!form.itemId || !form.openingQuantity) return;
    const qty = parseFloat(form.openingQuantity);

    const { error } = await supabase.from('items_opening').insert({
      item_id: form.itemId, stack_number: parseInt(form.stackNumber), opening_quantity: qty,
      opening_date: form.openingDate, remarks: form.remarks || null, added_by: userRole,
    });
    if (error) { setError(error.message); return; }

    // Push opening balance into live inventory
    const { data: existing } = await supabase.from('inventory').select('quantity').eq('item_id', form.itemId).eq('stack_number', parseInt(form.stackNumber)).maybeSingle();
    const current = existing?.quantity || 0;
    const { error: invErr } = await supabase.from('inventory').upsert(
      { item_id: form.itemId, stack_number: parseInt(form.stackNumber), quantity: current + qty },
      { onConflict: 'item_id,stack_number' }
    );
    if (invErr) setError(invErr.message);

    setForm((p) => ({ ...empty, itemId: p.itemId }));
  };

  return (
    <FormPanel
      title="Set Item Opening Balance"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('items_opening').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'opening_date', label: 'Date' },
        { key: 'item', label: 'Item', render: (r) => r.items?.item_name },
        { key: 'stack_number', label: 'Stack', render: (r) => `S${r.stack_number}` },
        { key: 'opening_quantity', label: 'Opening Qty' },
      ]}
    >
      <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Item</option>
        {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
      </select>
      <input type="number" value={form.stackNumber} onChange={(e) => setForm((p) => ({ ...p, stackNumber: e.target.value }))} placeholder="Stack No" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.openingQuantity} onChange={(e) => setForm((p) => ({ ...p, openingQuantity: e.target.value }))} placeholder="Opening Quantity" className="w-full px-3 py-2 border rounded-md" />
      <input type="date" value={form.openingDate} onChange={(e) => setForm((p) => ({ ...p, openingDate: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      <p className="text-xs text-gray-500">This adds directly to your live Inventory stock for that item/stack.</p>
    </FormPanel>
  );
}

// ---------------- Ledgers Opening ----------------
function LedgersOpening({ supabase, setError, userRole }) {
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { ledgerId: '', openingBalance: '', balanceType: 'debit', openingDate: todayStr(), remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'ledgers_opening', '*, ledgers(ledger_name, ledger_type)', setError, 'opening_date');

  const save = async () => {
    if (!form.ledgerId || !form.openingBalance) return;
    const { error } = await supabase.from('ledgers_opening').insert({
      ledger_id: form.ledgerId, opening_balance: parseFloat(form.openingBalance), balance_type: form.balanceType,
      opening_date: form.openingDate, remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  return (
    <FormPanel
      title="Set Ledger Opening Balance"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('ledgers_opening').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'opening_date', label: 'Date' },
        { key: 'ledger', label: 'Ledger', render: (r) => r.ledgers?.ledger_name },
        { key: 'opening_balance', label: 'Balance (₹)' },
        { key: 'balance_type', label: 'Dr/Cr' },
      ]}
    >
      <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Ledger</option>
        {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name} ({l.ledger_type})</option>)}
      </select>
      <input type="number" value={form.openingBalance} onChange={(e) => setForm((p) => ({ ...p, openingBalance: e.target.value }))} placeholder="Opening Balance (₹)" className="w-full px-3 py-2 border rounded-md" />
      <select value={form.balanceType} onChange={(e) => setForm((p) => ({ ...p, balanceType: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="debit">Debit</option>
        <option value="credit">Credit</option>
      </select>
      <input type="date" value={form.openingDate} onChange={(e) => setForm((p) => ({ ...p, openingDate: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}
