import React, { useState, useEffect } from 'react';
import { Trash2 } from 'lucide-react';

// ============================================================
// REQUIRED DATABASE SETUP — run once in the Supabase SQL editor:
//
// create table if not exists purchases (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id),
//   material_type text not null check (material_type in ('item','raw_material')),
//   item_id bigint references items(id),
//   raw_material_id bigint references raw_materials(id),
//   stack_number int,
//   quantity numeric not null,
//   rate numeric,
//   amount numeric,
//   vehicle_id bigint references vehicles(id),
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Sale needs a few optional new columns on your existing `records` table:
// alter table records add column if not exists ledger_id bigint references ledgers(id);
// alter table records add column if not exists vehicle_id bigint references vehicles(id);
// alter table records add column if not exists sale_agent_id bigint references sale_agents(id);
//
// -- Issue / Return (materials or items issued to workers/locations, and returns)
// create table if not exists issue_returns (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   direction text not null check (direction in ('issue','return')),
//   material_type text not null check (material_type in ('item','raw_material')),
//   item_id bigint references items(id),
//   raw_material_id bigint references raw_materials(id),
//   stack_number int,
//   quantity numeric not null,
//   issued_to text,
//   location_id bigint references locations(id),
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Credit Ledger Work (generic credit/debit voucher against any ledger)
// create table if not exists ledger_vouchers (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id) not null,
//   voucher_type text not null check (voucher_type in ('debit','credit')),
//   amount numeric not null,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Credit Vehicle Work (vehicle-linked work done on credit)
// create table if not exists vehicle_credit_work (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   vehicle_id bigint references vehicles(id) not null,
//   ledger_id bigint references ledgers(id),
//   work_description text,
//   amount numeric,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Orders (Order Master + Manage Order share this table)
// create table if not exists orders (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id),
//   item_id bigint references items(id),
//   quantity numeric not null,
//   rate numeric,
//   expected_date date,
//   status text not null default 'pending' check (status in ('pending','partial','fulfilled','cancelled')),
//   delivered_quantity numeric not null default 0,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Absent Voucher (labour attendance/absence)
// create table if not exists absent_vouchers (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id) not null,
//   reason text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// -- Misc Sale (quick sales outside the normal item catalog)
// create table if not exists misc_sales (
//   id bigint generated by default as identity primary key,
//   date date not null,
//   ledger_id bigint references ledgers(id),
//   customer_name text,
//   description text not null,
//   quantity numeric,
//   rate numeric,
//   amount numeric,
//   remarks text,
//   added_by text,
//   created_at timestamptz default now()
// );
//
// Don't forget to enable Realtime on each new table (same as your other
// tables) if you want it to live-sync.
// ============================================================

// Pass in your existing `supabase` client and `userRole` from App.js as props.
export default function TransactionModule({ supabase, userRole, subTab: subTabProp, onSubTabChange }) {
  const [internalSubTab, setInternalSubTab] = useState('purchase');
  const subTab = subTabProp || internalSubTab;
  const setSubTab = onSubTabChange || setInternalSubTab;
  const [error, setError] = useState('');

  const tabs = [
    ['purchase', '🛒 Purchase'],
    ['sale', '💰 Sale'],
    ['stockAdjustment', '📦 Stock Adjustment'],
    ['issueReturn', '🔁 Issue/Return'],
    ['creditLedger', '📒 Credit Ledger Work'],
    ['creditVehicle', '🚚 Credit Vehicle Work'],
    ['orders', '🧾 Orders'],
    ['absentVoucher', '🙅 Absent Voucher'],
    ['miscSale', '🧺 Misc Sale'],
  ];

  return (
    <div className="space-y-4">
      {error && (
        <div className="bg-red-50 border-l-4 border-red-500 p-3 rounded-lg">
          <p className="text-sm text-red-700">⚠️ {error}</p>
        </div>
      )}

      {!subTabProp && (
      <div className="flex gap-2 flex-wrap">
        {tabs.map(([key, label]) => (
          <button
            key={key}
            onClick={() => setSubTab(key)}
            className={`px-3 py-2 rounded-lg font-semibold text-xs ${subTab === key ? 'bg-red-800 text-white' : 'bg-white text-gray-700'}`}
          >
            {label}
          </button>
        ))}
      </div>
      )}

      {subTab === 'purchase' && <Purchase supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'sale' && <Sale supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'stockAdjustment' && <StockAdjustment supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'issueReturn' && <IssueReturn supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'creditLedger' && <CreditLedgerWork supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'creditVehicle' && <CreditVehicleWork supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'orders' && <Orders supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'absentVoucher' && <AbsentVoucher supabase={supabase} setError={setError} userRole={userRole} />}
      {subTab === 'miscSale' && <MiscSale supabase={supabase} setError={setError} userRole={userRole} />}
    </div>
  );
}

// ---------- shared helpers (same pattern as ProductionModule/MastersModule) ----------
function useSynced(supabase, table, selectStr, setError, orderCol = 'id') {
  const [rows, setRows] = useState([]);
  const load = async () => {
    const { data, error } = await supabase.from(table).select(selectStr || '*').order(orderCol, { ascending: false });
    if (error) setError(error.message); else setRows(data || []);
  };
  useEffect(() => {
    load();
    const ch = supabase.channel(`${table}-sync`)
      .on('postgres_changes', { event: '*', schema: 'public', table }, load).subscribe();
    return () => supabase.removeChannel(ch);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return { rows, load };
}

function useLookup(supabase, table, setError, filterFn) {
  const [rows, setRows] = useState([]);
  useEffect(() => {
    supabase.from(table).select('*').order('id').then(({ data, error }) => {
      if (error) setError(error.message); else setRows(filterFn ? (data || []).filter(filterFn) : (data || []));
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return rows;
}

function sumBy(rows, groupKeyFn, valueKey = 'quantity') {
  const totals = {};
  for (const r of rows) {
    const key = groupKeyFn(r);
    if (key === null || key === undefined) continue;
    totals[key] = (totals[key] || 0) + (r[valueKey] || 0);
  }
  return totals;
}

function StockGrid({ title, entries }) {
  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <h3 className="text-lg font-bold mb-3">{title}</h3>
      {entries.length === 0 ? (
        <p className="text-gray-400 text-sm">No data yet</p>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {entries.map(([label, val]) => (
            <div key={label} className="p-3 rounded-lg border-2 bg-blue-50 border-blue-200">
              <p className="text-xs font-bold truncate">{label}</p>
              <p className="text-xl font-bold text-blue-600">{typeof val === 'number' ? val.toLocaleString() : val}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function FormPanel({ title, children, onSave, tableRows, columns, onDelete }) {
  return (
    <div className="grid lg:grid-cols-3 gap-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl font-bold mb-4">{title}</h2>
        <div className="space-y-3">
          {children}
          <button onClick={onSave} className="w-full bg-red-700 text-white font-bold py-2 rounded-md">Save</button>
        </div>
      </div>
      <div className="lg:col-span-2 bg-white rounded-lg shadow-md p-6 overflow-x-auto">
        {tableRows.length === 0 ? (
          <p className="text-gray-400">No entries yet</p>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                {columns.map((c) => <th key={c.key} className="px-3 py-2 text-left">{c.label}</th>)}
                <th className="px-3 py-2">Del</th>
              </tr>
            </thead>
            <tbody>
              {tableRows.map((row) => (
                <tr key={row.id} className="border-b">
                  {columns.map((c) => (
                    <td key={c.key} className="px-3 py-2">{c.render ? c.render(row) : row[c.key]}</td>
                  ))}
                  <td className="px-3 py-2 text-center">
                    <button onClick={() => onDelete(row.id)} className="text-red-500"><Trash2 size={16} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

const todayStr = () => new Date().toISOString().split('T')[0];

// Fetch current inventory as a nested map { itemId: { stackNumber: qty } }, live-synced
function useInventoryMap(supabase, setError) {
  const [inv, setInv] = useState({});
  const load = async () => {
    const { data, error } = await supabase.from('inventory').select('*');
    if (error) { setError(error.message); return; }
    const map = {};
    for (const row of data || []) {
      if (!map[row.item_id]) map[row.item_id] = {};
      map[row.item_id][row.stack_number] = row.quantity;
    }
    setInv(map);
  };
  useEffect(() => {
    load();
    const ch = supabase.channel('inventory-sync-transaction')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'inventory' }, load).subscribe();
    return () => supabase.removeChannel(ch);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return { inv, reload: load };
}

async function upsertInventory(supabase, setError, itemId, stack, quantity) {
  const { error } = await supabase
    .from('inventory')
    .upsert({ item_id: itemId, stack_number: parseInt(stack), quantity }, { onConflict: 'item_id,stack_number' });
  if (error) setError(error.message);
}

// ---------------- Purchase ----------------
function Purchase({ supabase, setError, userRole }) {
  const items = useLookup(supabase, 'items', setError);
  const rawMaterials = useLookup(supabase, 'raw_materials', setError);
  const suppliers = useLookup(supabase, 'ledgers', setError, (l) => l.ledger_type === 'supplier');
  const vehicles = useLookup(supabase, 'vehicles', setError);
  const { inv, reload: reloadInv } = useInventoryMap(supabase, setError);

  const empty = {
    date: todayStr(), ledgerId: '', materialType: 'raw_material',
    materialId: '', stackNumber: '1', quantity: '', rate: '', vehicleId: '', remarks: '',
  };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(
    supabase, 'purchases',
    '*, ledgers(ledger_name), items(item_name), raw_materials(material_name, unit), vehicles(vehicle_number)',
    setError, 'date'
  );

  const save = async () => {
    if (!form.materialId || !form.quantity) return;
    const qty = parseFloat(form.quantity);
    const rate = form.rate ? parseFloat(form.rate) : null;
    const amount = rate ? qty * rate : null;

    const { error } = await supabase.from('purchases').insert({
      date: form.date, ledger_id: form.ledgerId || null, material_type: form.materialType,
      item_id: form.materialType === 'item' ? form.materialId : null,
      raw_material_id: form.materialType === 'raw_material' ? form.materialId : null,
      stack_number: form.materialType === 'item' ? parseInt(form.stackNumber) : null,
      quantity: qty, rate, amount, vehicle_id: form.vehicleId || null,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) { setError(error.message); return; }

    // Feed the purchase straight into the right stock ledger
    if (form.materialType === 'raw_material') {
      const { error: rmErr } = await supabase.from('raw_material_transactions').insert({
        date: form.date, material_id: form.materialId, txn_type: 'purchase',
        quantity: qty, remarks: form.remarks || null, added_by: userRole,
      });
      if (rmErr) setError(rmErr.message);
    } else {
      const current = inv[form.materialId]?.[form.stackNumber] || 0;
      await upsertInventory(supabase, setError, form.materialId, form.stackNumber, current + qty);
      reloadInv();
    }

    setForm((p) => ({ ...empty, materialType: p.materialType, ledgerId: p.ledgerId }));
  };

  const byLedger = sumBy(rows.filter((r) => r.amount), (r) => r.ledgers?.ledger_name || 'Cash Purchase', 'amount');

  return (
    <div className="space-y-4">
      <StockGrid title="Total Purchase Amount — by Supplier (₹)" entries={Object.entries(byLedger)} />
      <FormPanel
        title="Record Purchase"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('purchases').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'supplier', label: 'Supplier', render: (r) => r.ledgers?.ledger_name || '-' },
          { key: 'material', label: 'Material', render: (r) => r.material_type === 'item' ? r.items?.item_name : `${r.raw_materials?.material_name || ''} (${r.raw_materials?.unit || ''})` },
          { key: 'quantity', label: 'Qty' },
          { key: 'rate', label: 'Rate', render: (r) => r.rate ?? '-' },
          { key: 'amount', label: 'Amount (₹)', render: (r) => r.amount ?? '-' },
          { key: 'vehicle', label: 'Vehicle', render: (r) => r.vehicles?.vehicle_number || '-' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Supplier (optional / cash)</option>
          {suppliers.map((s) => <option key={s.id} value={s.id}>{s.ledger_name}</option>)}
        </select>
        <select value={form.materialType} onChange={(e) => setForm((p) => ({ ...p, materialType: e.target.value, materialId: '' }))} className="w-full px-3 py-2 border rounded-md">
          <option value="raw_material">Raw Material (coal, clay, diesel...)</option>
          <option value="item">Finished Item (brick stock)</option>
        </select>
        {form.materialType === 'raw_material' ? (
          <select value={form.materialId} onChange={(e) => setForm((p) => ({ ...p, materialId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
            <option value="">Select Material</option>
            {rawMaterials.map((m) => <option key={m.id} value={m.id}>{m.material_name}</option>)}
          </select>
        ) : (
          <>
            <select value={form.materialId} onChange={(e) => setForm((p) => ({ ...p, materialId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
              <option value="">Select Item</option>
              {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
            </select>
            <input type="number" value={form.stackNumber} onChange={(e) => setForm((p) => ({ ...p, stackNumber: e.target.value }))} placeholder="Stack No" className="w-full px-3 py-2 border rounded-md" />
          </>
        )}
        <input type="number" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} placeholder="Quantity" className="w-full px-3 py-2 border rounded-md" />
        <input type="number" value={form.rate} onChange={(e) => setForm((p) => ({ ...p, rate: e.target.value }))} placeholder="Rate (₹ per unit, optional)" className="w-full px-3 py-2 border rounded-md" />
        <select value={form.vehicleId} onChange={(e) => setForm((p) => ({ ...p, vehicleId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Vehicle (optional)</option>
          {vehicles.map((v) => <option key={v.id} value={v.id}>{v.vehicle_number}</option>)}
        </select>
        <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
    </div>
  );
}

// ---------------- Sale ----------------
function Sale({ supabase, setError, userRole }) {
  const items = useLookup(supabase, 'items', setError);
  const customers = useLookup(supabase, 'ledgers', setError, (l) => l.ledger_type === 'customer');
  const vehicles = useLookup(supabase, 'vehicles', setError);
  const saleAgents = useLookup(supabase, 'sale_agents', setError);
  const { inv, reload: reloadInv } = useInventoryMap(supabase, setError);

  const empty = {
    date: todayStr(), ledgerId: '', customerName: '', driverName: '', slipNumber: '',
    itemId: '', stackNumber: '', soldQuantity: '', salePrice: '', vehicleId: '', saleAgentId: '',
  };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(
    supabase, 'records',
    '*, items(item_name), ledgers(ledger_name), vehicles(vehicle_number), sale_agents(agent_name)',
    setError, 'date'
  );
  const salesRows = rows.filter((r) => r.type === 'sales');

  const save = async () => {
    const custName = form.ledgerId ? (customers.find((c) => c.id === form.ledgerId)?.ledger_name || '') : form.customerName;
    if (!custName || !form.slipNumber || !form.soldQuantity || !form.stackNumber || !form.itemId) return;

    const qty = parseInt(form.soldQuantity);
    const available = inv[form.itemId]?.[form.stackNumber] || 0;
    if (qty > available) { setError('Not enough stock in that stack'); return; }

    await upsertInventory(supabase, setError, form.itemId, form.stackNumber, available - qty);
    reloadInv();

    const { error } = await supabase.from('records').insert({
      type: 'sales', date: form.date, ledger_id: form.ledgerId || null,
      customer_name: custName, driver_name: form.driverName || null, slip_number: form.slipNumber,
      item_id: form.itemId, stack_number: parseInt(form.stackNumber), sold_quantity: qty,
      total_amount: form.salePrice ? (qty / 1000) * parseFloat(form.salePrice) : null,
      vehicle_id: form.vehicleId || null, sale_agent_id: form.saleAgentId || null, added_by: userRole,
    });
    if (error) setError(error.message);
    setForm(empty);
  };

  return (
    <FormPanel
      title="Record Sale"
      onSave={save}
      tableRows={salesRows}
      onDelete={async (id) => { const { error } = await supabase.from('records').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'date', label: 'Date' },
        { key: 'customer_name', label: 'Customer' },
        { key: 'item', label: 'Item', render: (r) => r.items?.item_name },
        { key: 'sold_quantity', label: 'Qty' },
        { key: 'total_amount', label: 'Amount (₹)', render: (r) => r.total_amount ? Number(r.total_amount).toFixed(2) : '-' },
        { key: 'vehicle', label: 'Vehicle', render: (r) => r.vehicles?.vehicle_number || '-' },
        { key: 'agent', label: 'Agent', render: (r) => r.sale_agents?.agent_name || '-' },
      ]}
    >
      <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Customer (or type below)</option>
        {customers.map((c) => <option key={c.id} value={c.id}>{c.ledger_name}</option>)}
      </select>
      {!form.ledgerId && (
        <input type="text" value={form.customerName} onChange={(e) => setForm((p) => ({ ...p, customerName: e.target.value }))} placeholder="Customer Name" className="w-full px-3 py-2 border rounded-md" />
      )}
      <input type="text" value={form.driverName} onChange={(e) => setForm((p) => ({ ...p, driverName: e.target.value }))} placeholder="Driver" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.slipNumber} onChange={(e) => setForm((p) => ({ ...p, slipNumber: e.target.value }))} placeholder="Slip #" className="w-full px-3 py-2 border rounded-md" />
      <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value, stackNumber: '' }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Item</option>
        {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
      </select>
      <select value={form.stackNumber} onChange={(e) => setForm((p) => ({ ...p, stackNumber: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Stack</option>
        {Object.entries(inv[form.itemId] || {}).filter(([, qty]) => qty > 0).map(([stack, qty]) => (
          <option key={stack} value={stack}>S{stack} ({qty} avail)</option>
        ))}
      </select>
      <input type="number" value={form.soldQuantity} onChange={(e) => setForm((p) => ({ ...p, soldQuantity: e.target.value }))} placeholder="Qty" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.salePrice} onChange={(e) => setForm((p) => ({ ...p, salePrice: e.target.value }))} placeholder="₹ / 1000" className="w-full px-3 py-2 border rounded-md" />
      <select value={form.vehicleId} onChange={(e) => setForm((p) => ({ ...p, vehicleId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Vehicle (optional)</option>
        {vehicles.map((v) => <option key={v.id} value={v.id}>{v.vehicle_number}</option>)}
      </select>
      <select value={form.saleAgentId} onChange={(e) => setForm((p) => ({ ...p, saleAgentId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Sale Agent (optional)</option>
        {saleAgents.map((a) => <option key={a.id} value={a.id}>{a.agent_name}</option>)}
      </select>
    </FormPanel>
  );
}

// ---------------- Stock Adjustment ----------------
function StockAdjustment({ supabase, setError }) {
  const items = useLookup(supabase, 'items', setError);
  const { inv, reload } = useInventoryMap(supabase, setError);
  const empty = { itemId: '', stackNumber: '', quantity: '' };
  const [form, setForm] = useState(empty);

  const totalByItem = (itemId) => Object.values(inv[itemId] || {}).reduce((s, q) => s + q, 0);

  const save = async () => {
    if (!form.quantity || !form.stackNumber || !form.itemId) return;
    const qty = parseInt(form.quantity);
    const current = inv[form.itemId]?.[form.stackNumber] || 0;
    if (current + qty < 0) { setError('Adjustment would make stock negative'); return; }
    await upsertInventory(supabase, setError, form.itemId, form.stackNumber, current + qty);
    reload();
    setForm((p) => ({ itemId: p.itemId, stackNumber: '', quantity: '' }));
  };

  return (
    <div className="grid lg:grid-cols-3 gap-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl font-bold mb-4">Adjust Inventory</h2>
        <div className="space-y-3">
          <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
            <option value="">Select Item</option>
            {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
          </select>
          <input type="number" value={form.stackNumber} onChange={(e) => setForm((p) => ({ ...p, stackNumber: e.target.value }))} placeholder="Stack No" className="w-full px-3 py-2 border rounded-md" />
          <input type="number" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} placeholder="Qty (+/-)" className="w-full px-3 py-2 border rounded-md" />
          <button onClick={save} className="w-full bg-purple-500 text-white font-bold py-2 rounded-md">Adjust</button>
        </div>
        <p className="text-xs text-gray-500 mt-2">Use a negative quantity to reduce stock (e.g. breakage).</p>
      </div>
      <div className="lg:col-span-2 bg-white rounded-lg shadow-md p-6">
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2">
          {items.map((it) => {
            const total = totalByItem(it.id);
            return (
              <div key={it.id} className={`p-3 rounded-lg border-2 ${total === 0 ? 'bg-red-50 border-red-300' : 'bg-green-50 border-green-300'}`}>
                <p className="text-xs font-bold">{it.item_name}</p>
                <p className={`text-2xl font-bold ${total === 0 ? 'text-red-600' : 'text-green-600'}`}>{total}</p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ---------------- Issue / Return ----------------
function IssueReturn({ supabase, setError, userRole }) {
  const items = useLookup(supabase, 'items', setError);
  const rawMaterials = useLookup(supabase, 'raw_materials', setError);
  const locations = useLookup(supabase, 'locations', setError);
  const { inv, reload: reloadInv } = useInventoryMap(supabase, setError);

  const empty = {
    date: todayStr(), direction: 'issue', materialType: 'raw_material', materialId: '',
    stackNumber: '1', quantity: '', issuedTo: '', locationId: '', remarks: '',
  };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(
    supabase, 'issue_returns',
    '*, items(item_name), raw_materials(material_name, unit), locations(location_name)',
    setError, 'date'
  );

  const save = async () => {
    if (!form.materialId || !form.quantity) return;
    const qty = parseFloat(form.quantity);

    const { error } = await supabase.from('issue_returns').insert({
      date: form.date, direction: form.direction, material_type: form.materialType,
      item_id: form.materialType === 'item' ? form.materialId : null,
      raw_material_id: form.materialType === 'raw_material' ? form.materialId : null,
      stack_number: form.materialType === 'item' ? parseInt(form.stackNumber) : null,
      quantity: qty, issued_to: form.issuedTo || null, location_id: form.locationId || null,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) { setError(error.message); return; }

    // Issue = stock out, Return = stock in
    const signedQty = form.direction === 'issue' ? -qty : qty;
    if (form.materialType === 'raw_material') {
      const { error: rmErr } = await supabase.from('raw_material_transactions').insert({
        date: form.date, material_id: form.materialId,
        txn_type: form.direction === 'issue' ? 'usage' : 'purchase',
        quantity: qty, location_id: form.locationId || null,
        remarks: form.remarks || (form.direction === 'issue' ? `Issued to ${form.issuedTo || 'worker'}` : `Returned by ${form.issuedTo || 'worker'}`),
        added_by: userRole,
      });
      if (rmErr) setError(rmErr.message);
    } else {
      const current = inv[form.materialId]?.[form.stackNumber] || 0;
      if (current + signedQty < 0) { setError('Not enough stock to issue'); return; }
      await upsertInventory(supabase, setError, form.materialId, form.stackNumber, current + signedQty);
      reloadInv();
    }

    setForm((p) => ({ ...empty, materialType: p.materialType, direction: p.direction }));
  };

  return (
    <FormPanel
      title="Record Issue / Return"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('issue_returns').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'date', label: 'Date' },
        { key: 'direction', label: 'Type', render: (r) => r.direction === 'issue' ? '🔻 Issue' : '🔺 Return' },
        { key: 'material', label: 'Material', render: (r) => r.material_type === 'item' ? r.items?.item_name : `${r.raw_materials?.material_name || ''} (${r.raw_materials?.unit || ''})` },
        { key: 'quantity', label: 'Qty' },
        { key: 'issued_to', label: 'To/From' },
        { key: 'location', label: 'Location', render: (r) => r.locations?.location_name || '-' },
      ]}
    >
      <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <select value={form.direction} onChange={(e) => setForm((p) => ({ ...p, direction: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="issue">Issue (stock out to worker/site)</option>
        <option value="return">Return (stock back in)</option>
      </select>
      <select value={form.materialType} onChange={(e) => setForm((p) => ({ ...p, materialType: e.target.value, materialId: '' }))} className="w-full px-3 py-2 border rounded-md">
        <option value="raw_material">Raw Material</option>
        <option value="item">Finished Item</option>
      </select>
      {form.materialType === 'raw_material' ? (
        <select value={form.materialId} onChange={(e) => setForm((p) => ({ ...p, materialId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Select Material</option>
          {rawMaterials.map((m) => <option key={m.id} value={m.id}>{m.material_name}</option>)}
        </select>
      ) : (
        <>
          <select value={form.materialId} onChange={(e) => setForm((p) => ({ ...p, materialId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
            <option value="">Select Item</option>
            {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
          </select>
          <input type="number" value={form.stackNumber} onChange={(e) => setForm((p) => ({ ...p, stackNumber: e.target.value }))} placeholder="Stack No" className="w-full px-3 py-2 border rounded-md" />
        </>
      )}
      <input type="number" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} placeholder="Quantity" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.issuedTo} onChange={(e) => setForm((p) => ({ ...p, issuedTo: e.target.value }))} placeholder="Issued To / Returned By (worker/party name)" className="w-full px-3 py-2 border rounded-md" />
      <select value={form.locationId} onChange={(e) => setForm((p) => ({ ...p, locationId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Location (optional)</option>
        {locations.map((l) => <option key={l.id} value={l.id}>{l.location_name}</option>)}
      </select>
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}

// ---------------- Credit Ledger Work ----------------
function CreditLedgerWork({ supabase, setError, userRole }) {
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { date: todayStr(), ledgerId: '', voucherType: 'debit', amount: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'ledger_vouchers', '*, ledgers(ledger_name, ledger_type)', setError, 'date');

  const save = async () => {
    if (!form.ledgerId || !form.amount) return;
    const { error } = await supabase.from('ledger_vouchers').insert({
      date: form.date, ledger_id: form.ledgerId, voucher_type: form.voucherType,
      amount: parseFloat(form.amount), remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, ledgerId: p.ledgerId }));
  };

  const balances = sumBy(
    rows.map((r) => ({ ...r, signedAmount: r.voucher_type === 'debit' ? r.amount : -r.amount })),
    (r) => r.ledgers?.ledger_name, 'signedAmount'
  );

  return (
    <div className="space-y-4">
      <StockGrid title="Net Movement by Ledger (₹, +debit / -credit)" entries={Object.entries(balances)} />
      <FormPanel
        title="Add Ledger Voucher"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('ledger_vouchers').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'ledger', label: 'Ledger', render: (r) => r.ledgers?.ledger_name },
          { key: 'voucher_type', label: 'Type' },
          { key: 'amount', label: 'Amount (₹)' },
          { key: 'remarks', label: 'Remarks' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Select Ledger</option>
          {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name} ({l.ledger_type})</option>)}
        </select>
        <select value={form.voucherType} onChange={(e) => setForm((p) => ({ ...p, voucherType: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="debit">Debit (they owe us more)</option>
          <option value="credit">Credit (we owe them / they paid)</option>
        </select>
        <input type="number" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} placeholder="Amount (₹)" className="w-full px-3 py-2 border rounded-md" />
        <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
    </div>
  );
}

// ---------------- Credit Vehicle Work ----------------
function CreditVehicleWork({ supabase, setError, userRole }) {
  const vehicles = useLookup(supabase, 'vehicles', setError);
  const ledgers = useLookup(supabase, 'ledgers', setError);
  const empty = { date: todayStr(), vehicleId: '', ledgerId: '', workDescription: '', amount: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'vehicle_credit_work', '*, vehicles(vehicle_number), ledgers(ledger_name)', setError, 'date');

  const save = async () => {
    if (!form.vehicleId || !form.workDescription) return;
    const { error } = await supabase.from('vehicle_credit_work').insert({
      date: form.date, vehicle_id: form.vehicleId, ledger_id: form.ledgerId || null,
      work_description: form.workDescription, amount: form.amount ? parseFloat(form.amount) : null,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, vehicleId: p.vehicleId }));
  };

  const byVehicle = sumBy(rows.filter((r) => r.amount), (r) => r.vehicles?.vehicle_number, 'amount');

  return (
    <div className="space-y-4">
      <StockGrid title="Total Credit Work Amount — by Vehicle (₹)" entries={Object.entries(byVehicle)} />
      <FormPanel
        title="Add Credit Vehicle Work"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('vehicle_credit_work').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'vehicle', label: 'Vehicle', render: (r) => r.vehicles?.vehicle_number },
          { key: 'ledger', label: 'Party', render: (r) => r.ledgers?.ledger_name || '-' },
          { key: 'work_description', label: 'Work' },
          { key: 'amount', label: 'Amount (₹)', render: (r) => r.amount ?? '-' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.vehicleId} onChange={(e) => setForm((p) => ({ ...p, vehicleId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Select Vehicle</option>
          {vehicles.map((v) => <option key={v.id} value={v.id}>{v.vehicle_number}</option>)}
        </select>
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Party Ledger (optional)</option>
          {ledgers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name}</option>)}
        </select>
        <input type="text" value={form.workDescription} onChange={(e) => setForm((p) => ({ ...p, workDescription: e.target.value }))} placeholder="Work Description (repair, freight job, etc.)" className="w-full px-3 py-2 border rounded-md" />
        <input type="number" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} placeholder="Amount (₹, optional)" className="w-full px-3 py-2 border rounded-md" />
        <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
    </div>
  );
}

// ---------------- Orders (Order Master + Manage Order) ----------------
function Orders({ supabase, setError, userRole }) {
  const [mode, setMode] = useState('create');
  const customers = useLookup(supabase, 'ledgers', setError, (l) => l.ledger_type === 'customer');
  const items = useLookup(supabase, 'items', setError);
  const empty = { date: todayStr(), ledgerId: '', itemId: '', quantity: '', rate: '', expectedDate: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows, load } = useSynced(supabase, 'orders', '*, ledgers(ledger_name), items(item_name)', setError, 'date');

  const save = async () => {
    if (!form.ledgerId || !form.itemId || !form.quantity) return;
    const { error } = await supabase.from('orders').insert({
      date: form.date, ledger_id: form.ledgerId, item_id: form.itemId,
      quantity: parseFloat(form.quantity), rate: form.rate ? parseFloat(form.rate) : null,
      expected_date: form.expectedDate || null, remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  const updateStatus = async (order, deliveredQuantity, status) => {
    const { error } = await supabase.from('orders').update({ delivered_quantity: deliveredQuantity, status }).eq('id', order.id);
    if (error) setError(error.message); else load();
  };

  const pending = rows.filter((r) => r.status !== 'fulfilled' && r.status !== 'cancelled');

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        <button onClick={() => setMode('create')} className={`px-3 py-2 rounded-lg text-sm font-semibold ${mode === 'create' ? 'bg-red-800 text-white' : 'bg-gray-100'}`}>Order Master (New Order)</button>
        <button onClick={() => setMode('manage')} className={`px-3 py-2 rounded-lg text-sm font-semibold ${mode === 'manage' ? 'bg-red-800 text-white' : 'bg-gray-100'}`}>Manage Orders ({pending.length} pending)</button>
      </div>

      {mode === 'create' && (
        <FormPanel
          title="Create Order"
          onSave={save}
          tableRows={rows}
          onDelete={async (id) => { const { error } = await supabase.from('orders').delete().eq('id', id); if (error) setError(error.message); }}
          columns={[
            { key: 'date', label: 'Date' },
            { key: 'ledger', label: 'Customer', render: (r) => r.ledgers?.ledger_name },
            { key: 'item', label: 'Item', render: (r) => r.items?.item_name },
            { key: 'quantity', label: 'Qty' },
            { key: 'delivered_quantity', label: 'Delivered' },
            { key: 'status', label: 'Status' },
          ]}
        >
          <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
          <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
            <option value="">Select Customer</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.ledger_name}</option>)}
          </select>
          <select value={form.itemId} onChange={(e) => setForm((p) => ({ ...p, itemId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
            <option value="">Select Item</option>
            {items.map((it) => <option key={it.id} value={it.id}>{it.item_name}</option>)}
          </select>
          <input type="number" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} placeholder="Quantity Ordered" className="w-full px-3 py-2 border rounded-md" />
          <input type="number" value={form.rate} onChange={(e) => setForm((p) => ({ ...p, rate: e.target.value }))} placeholder="Rate (₹/1000, optional)" className="w-full px-3 py-2 border rounded-md" />
          <input type="date" value={form.expectedDate} onChange={(e) => setForm((p) => ({ ...p, expectedDate: e.target.value }))} placeholder="Expected Delivery" className="w-full px-3 py-2 border rounded-md" />
          <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
        </FormPanel>
      )}

      {mode === 'manage' && (
        <div className="bg-white rounded-lg shadow-md p-6 overflow-x-auto">
          {pending.length === 0 ? (
            <p className="text-gray-400">No pending orders</p>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-3 py-2 text-left">Date</th>
                  <th className="px-3 py-2 text-left">Customer</th>
                  <th className="px-3 py-2 text-left">Item</th>
                  <th className="px-3 py-2 text-left">Ordered</th>
                  <th className="px-3 py-2 text-left">Delivered</th>
                  <th className="px-3 py-2 text-left">Status</th>
                  <th className="px-3 py-2">Actions</th>
                </tr>
              </thead>
              <tbody>
                {pending.map((r) => (
                  <OrderRow key={r.id} order={r} onUpdate={updateStatus} />
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
}

function OrderRow({ order, onUpdate }) {
  const [delivered, setDelivered] = useState(order.delivered_quantity || 0);
  return (
    <tr className="border-b">
      <td className="px-3 py-2">{order.date}</td>
      <td className="px-3 py-2">{order.ledgers?.ledger_name}</td>
      <td className="px-3 py-2">{order.items?.item_name}</td>
      <td className="px-3 py-2">{order.quantity}</td>
      <td className="px-3 py-2">
        <input type="number" value={delivered} onChange={(e) => setDelivered(e.target.value)} className="w-20 px-2 py-1 border rounded-md" />
      </td>
      <td className="px-3 py-2 capitalize">{order.status}</td>
      <td className="px-3 py-2 text-center space-x-2">
        <button
          onClick={() => onUpdate(order, parseFloat(delivered) || 0, parseFloat(delivered) >= order.quantity ? 'fulfilled' : 'partial')}
          className="text-xs bg-green-500 text-white px-2 py-1 rounded-md"
        >
          Update
        </button>
        <button onClick={() => onUpdate(order, order.delivered_quantity || 0, 'cancelled')} className="text-xs bg-red-500 text-white px-2 py-1 rounded-md">
          Cancel
        </button>
      </td>
    </tr>
  );
}

// ---------------- Absent Voucher ----------------
function AbsentVoucher({ supabase, setError, userRole }) {
  const labourers = useLookup(supabase, 'ledgers', setError, (l) => l.ledger_type === 'labour');
  const empty = { date: todayStr(), ledgerId: '', reason: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'absent_vouchers', '*, ledgers(ledger_name)', setError, 'date');

  const save = async () => {
    if (!form.ledgerId) return;
    const { error } = await supabase.from('absent_vouchers').insert({
      date: form.date, ledger_id: form.ledgerId, reason: form.reason || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm(empty);
  };

  const absenceCounts = {};
  for (const r of rows) {
    const name = r.ledgers?.ledger_name;
    if (!name) continue;
    absenceCounts[name] = (absenceCounts[name] || 0) + 1;
  }

  return (
    <div className="space-y-4">
      <StockGrid title="Total Absences — by Labour" entries={Object.entries(absenceCounts)} />
      <FormPanel
        title="Record Absence"
        onSave={save}
        tableRows={rows}
        onDelete={async (id) => { const { error } = await supabase.from('absent_vouchers').delete().eq('id', id); if (error) setError(error.message); }}
        columns={[
          { key: 'date', label: 'Date' },
          { key: 'ledger', label: 'Labour', render: (r) => r.ledgers?.ledger_name },
          { key: 'reason', label: 'Reason' },
        ]}
      >
        <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
        <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
          <option value="">Select Labour</option>
          {labourers.map((l) => <option key={l.id} value={l.id}>{l.ledger_name}</option>)}
        </select>
        <input type="text" value={form.reason} onChange={(e) => setForm((p) => ({ ...p, reason: e.target.value }))} placeholder="Reason (optional)" className="w-full px-3 py-2 border rounded-md" />
      </FormPanel>
      {labourers.length === 0 && (
        <p className="text-xs text-gray-500">No labour ledgers found — add workers in Masters → Ledger with type "Labour" first.</p>
      )}
    </div>
  );
}

// ---------------- Misc Sale ----------------
function MiscSale({ supabase, setError, userRole }) {
  const customers = useLookup(supabase, 'ledgers', setError, (l) => l.ledger_type === 'customer');
  const empty = { date: todayStr(), ledgerId: '', customerName: '', description: '', quantity: '', rate: '', remarks: '' };
  const [form, setForm] = useState(empty);
  const { rows } = useSynced(supabase, 'misc_sales', '*, ledgers(ledger_name)', setError, 'date');

  const save = async () => {
    const custName = form.ledgerId ? (customers.find((c) => c.id === form.ledgerId)?.ledger_name || '') : form.customerName;
    if (!form.description) return;
    const qty = form.quantity ? parseFloat(form.quantity) : null;
    const rate = form.rate ? parseFloat(form.rate) : null;
    const amount = qty && rate ? qty * rate : null;

    const { error } = await supabase.from('misc_sales').insert({
      date: form.date, ledger_id: form.ledgerId || null, customer_name: custName || null,
      description: form.description, quantity: qty, rate, amount,
      remarks: form.remarks || null, added_by: userRole,
    });
    if (error) setError(error.message); else setForm((p) => ({ ...empty, ledgerId: p.ledgerId }));
  };

  return (
    <FormPanel
      title="Record Misc Sale"
      onSave={save}
      tableRows={rows}
      onDelete={async (id) => { const { error } = await supabase.from('misc_sales').delete().eq('id', id); if (error) setError(error.message); }}
      columns={[
        { key: 'date', label: 'Date' },
        { key: 'customer', label: 'Customer', render: (r) => r.ledgers?.ledger_name || r.customer_name || '-' },
        { key: 'description', label: 'Description' },
        { key: 'quantity', label: 'Qty', render: (r) => r.quantity ?? '-' },
        { key: 'amount', label: 'Amount (₹)', render: (r) => r.amount ?? '-' },
      ]}
    >
      <input type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} className="w-full px-3 py-2 border rounded-md" />
      <select value={form.ledgerId} onChange={(e) => setForm((p) => ({ ...p, ledgerId: e.target.value }))} className="w-full px-3 py-2 border rounded-md">
        <option value="">Select Customer (or type below)</option>
        {customers.map((c) => <option key={c.id} value={c.id}>{c.ledger_name}</option>)}
      </select>
      {!form.ledgerId && (
        <input type="text" value={form.customerName} onChange={(e) => setForm((p) => ({ ...p, customerName: e.target.value }))} placeholder="Customer Name (optional)" className="w-full px-3 py-2 border rounded-md" />
      )}
      <input type="text" value={form.description} onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))} placeholder="What was sold (e.g. brick dust, scrap)" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} placeholder="Quantity (optional)" className="w-full px-3 py-2 border rounded-md" />
      <input type="number" value={form.rate} onChange={(e) => setForm((p) => ({ ...p, rate: e.target.value }))} placeholder="Rate (optional)" className="w-full px-3 py-2 border rounded-md" />
      <input type="text" value={form.remarks} onChange={(e) => setForm((p) => ({ ...p, remarks: e.target.value }))} placeholder="Remarks" className="w-full px-3 py-2 border rounded-md" />
    </FormPanel>
  );
}
